package pitcher

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestShouldGetPathValueOnComplexPaths(t *testing.T) {

	resp := `{"state":"SP","cities":["MOGI-MIRIM","MOGI-GUAÇU","ESTIVA GERBI","VINHEDO","VARGEM GRANDE DO SUL","VALINHOS","TAPIRATIBA","TAMBAÚ","SUMARÉ","SOCORRO","SERRA NEGRA","SÃO SEBASTIÃO DA GRAMA","SÃO PEDRO","SÃO JOSÉ DO RIO PARDO","SÃO JOÃO DA BOA VISTA","SANTO ANTÔNIO DO JARDIM","SANTO ANTÔNIO DE POSSE","SANTA RITA DO PASSA QUATRO","SANTA MARIA DA SERRA","SANTA GERTRUDES","SANTA CRUZ DAS PALMEIRAS","SANTA CRUZ DA CONCEIÇÃO","SANTA BÁRBARA D'OESTE","SALTINHO","RIO DAS PEDRAS","RIO CLARO","RAFARD","PORTO FERREIRA","PIRASSUNUNGA","PIRACICABA","PEDREIRA","PAULÍNIA","NOVA ODESSA","MONTE MOR","MONTE ALEGRE DO SUL","MOMBUCA","MOCOCA","LOUVEIRA","LINDÓIA","LIMEIRA","LEME","JAGUARIÚNA","ITOBI","ITIRAPINA","ITAPIRA","IRACEMÁPOLIS","IPEÚNA","INDAIATUBA","HORTOLÂNDIA","HOLAMBRA","ESPÍRITO SANTO DO PINHAL","ENGENHEIRO COELHO","ELIAS FAUSTO","DIVINOLÂNDIA","DESCALVADO","COSMÓPOLIS","CORUMBATAÍ","CORDEIRÓPOLIS","CONCHAL","CHARQUEADA","CASA BRANCA","CAPIVARI","CAMPINAS","CACONDE","ARTUR NOGUEIRA","ARARAS","ANALÂNDIA","AMPARO","AMERICANA","ÁGUAS DE SÃO PEDRO","ÁGUAS DE LINDÓIA","ÁGUAS DA PRATA","AGUAÍ"]}`
	f := Extract("key", "cities.5")

	s := NewMemoryRWSession(make(map[string]string))

	f(&Request{}, &Response{Body: resp}, s)

	v, ok := s.Get("key")

	assert.True(t, ok)
	assert.Equal(t, "VALINHOS", v)

}
